on:
    pull_request:
      types: [closed]
      branches:
        - main
      paths:
        - ".github/workflows/infrastructure.yml"
        - "infrastructure/**"

name: Deploy infrastructure
jobs:
 deploy:
    #chekout the code
    - name: Checkout
      uses: actions/checkout@main

    # Login to Azure
    - name: Login via Azure CLI
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Deploy infrastructure
    id: deploy
    uses: azure/arm-deploy@v1
    with:
        resourceGroupName: ${{ vars.AZURE_RG }}
        template: infrastructure/bicep/deploy-container-infra.bicep
        deploymentName: deploy-infra--${{ steps.params.outputs.commit_id }}
        deploymentMode: Incremental
        failOnStdErr: true