on:
    pull_request:
      types: [closed]
      branches:
        - main
      paths:
        - ".github/workflows/infrastructure.yml"
        - "infrastructure/**"
    workflow_dispatch:

name: Deploy infrastructure
permissions:
    id-token: write
    contents: read
jobs:
 deploy:
  runs-on: ubuntu-latest
  steps:
    #chekout the code
    - name: Checkout
      uses: actions/checkout@main

    # Login to Azure with OIDC
    - name: Login via with OIDC
      id: login
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    # Deploy infrastructure
    - name: Deploy infrastructure
      id: deploy
      uses: azure/arm-deploy@v2
      with:
        scope: resourcegroup
        resourceGroupName: ${{ vars.AZURE_RG }}
        template: infrastructure/bicep/deploy-infra.bicep
        deploymentName: deploy-infra--${{ github.sha }}
        deploymentMode: Incremental
        failOnStdErr: true
